FROM registry.access.redhat.com/ubi8/ubi:8.8 as java-builder
LABEL maintainer="OpsMx"

ARG TARGETARCH


ENV KUBECTL_RELEASE=1.22.0
ENV AWS_CLI_S3_CMD=2.0.2
ENV AWS_AIM_AUTHENTICATOR_VERSION=0.5.9
ENV GOOGLE_CLOUD_SDK_VERSION=435.0.0
ENV ECR_TOKEN_VERSION=v1.0.2

ENV PATH "$PATH:/usr/local/bin/:/opt/google-cloud-sdk/bin/:/usr/local/bin/aws-iam-authenticator"

USER root

RUN yum -y install  wget git

RUN mkdir -p /opt/jaeger
COPY jaeger/opentelemetry-javaagent.jar /opt/jaeger/opentelemetry-javaagent.jar

#RUN yum -y remove  tar  curl 
#RUN yum -y remove  vim  jq unzip 
RUN yum -y remove clean all && rm -rf /var/cache



RUN adduser spinnaker
RUN mkdir -p /opt/clouddriver/plugins


ARG CUSTOMPLUGIN_RELEASEORG
ENV CUSTOMPLUGIN_RELEASEORG=${CUSTOMPLUGIN_RELEASEORG}

ARG CUSTOMPLUGIN_RELEASEREPO
ENV CUSTOMPLUGIN_RELEASEREPO=${CUSTOMPLUGIN_RELEASEREPO}

ARG CUSTOMPLUGIN_RELEASEVERSION
ENV CUSTOMPLUGIN_RELEASEVERSION=${CUSTOMPLUGIN_RELEASEVERSION}


RUN wget -O Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASEVERSION}-SNAPSHOT.zip -c https://github.com/${CUSTOMPLUGIN_RELEASEORG}/${CUSTOMPLUGIN_RELEASEREPO}/releases/download/${CUSTOMPLUGIN_RELEASEVERSION}/armory-observability-plugin-${CUSTOMPLUGIN_RELEASEVERSION}.zip -P /opt/clouddriver/plugins 
RUN mv Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASEVERSION}-SNAPSHOT.zip /opt/clouddriver/plugins/


RUN chmod -R 777 /opt/clouddriver/plugins/
RUN chown -R spinnaker:spinnaker /opt/

RUN mkdir -p /etc/pki/tls/certs
RUN chmod -R 777 /etc/pki/tls/certs
RUN chmod -R 777 /var/
RUN chown -R spinnaker:spinnaker /var
USER spinnaker
ENV SLEEP_TIME=10s
CMD  sleep $SLEEP_TIME ; "/opt/clouddriver/bin/clouddriver"
#CMD  sleep 180s ; "/opt/clouddriver/bin/clouddriver"

